// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoe5lm8BuE1w2_o_vt_8Ne4K_d6RbZ3n4',
    appId: '1:386289257828:web:7dcfe4bd6e74dca3adbe71',
    messagingSenderId: '386289257828',
    projectId: 'taf-match',
    authDomain: 'taf-match.firebaseapp.com',
    storageBucket: 'taf-match.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Q7vtQ3HDmmeIDvZI1XXYHZOqcczNijQ',
    appId: '1:386289257828:android:f3e123ae8463df88adbe71',
    messagingSenderId: '386289257828',
    projectId: 'taf-match',
    storageBucket: 'taf-match.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMhRL2b8GVL5JDl4RdmpKuqkWGnUm9tTo',
    appId: '1:386289257828:ios:5049add1e5fae438adbe71',
    messagingSenderId: '386289257828',
    projectId: 'taf-match',
    storageBucket: 'taf-match.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMhRL2b8GVL5JDl4RdmpKuqkWGnUm9tTo',
    appId: '1:386289257828:ios:5049add1e5fae438adbe71',
    messagingSenderId: '386289257828',
    projectId: 'taf-match',
    storageBucket: 'taf-match.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoe5lm8BuE1w2_o_vt_8Ne4K_d6RbZ3n4',
    appId: '1:386289257828:web:f5a2996bf2036609adbe71',
    messagingSenderId: '386289257828',
    projectId: 'taf-match',
    authDomain: 'taf-match.firebaseapp.com',
    storageBucket: 'taf-match.firebasestorage.app',
  );
}
