// Mocks generated by Mockito from annotations
// in taf_match/test/views/jp_applicants_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taf_match/models/application_model.dart' as _i4;
import 'package:taf_match/models/review_model.dart' as _i8;
import 'package:taf_match/models/user_model.dart' as _i6;
import 'package:taf_match/repositories/firestore_application_repository.dart'
    as _i2;
import 'package:taf_match/repositories/firestore_review_repository.dart' as _i7;
import 'package:taf_match/repositories/firestore_user_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreApplicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreApplicationRepository extends _i1.Mock
    implements _i2.FirestoreApplicationRepository {
  MockFirestoreApplicationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> apply(_i4.Application? application) => (super.noSuchMethod(
        Invocation.method(
          #apply,
          [application],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancel(String? applicationId) => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [applicationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Application>> watchByStudent(String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchByStudent,
          [studentId],
        ),
        returnValue: _i3.Stream<List<_i4.Application>>.empty(),
      ) as _i3.Stream<List<_i4.Application>>);

  @override
  _i3.Stream<List<_i4.Application>> watchByJob(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchByJob,
          [jobId],
        ),
        returnValue: _i3.Stream<List<_i4.Application>>.empty(),
      ) as _i3.Stream<List<_i4.Application>>);

  @override
  _i3.Future<void> updateStatus(
    String? applicationId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            applicationId,
            status,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FirestoreUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreUserRepository extends _i1.Mock
    implements _i5.FirestoreUserRepository {
  MockFirestoreUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createProfile(_i6.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [user],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.UserModel?> getProfile(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [uid],
        ),
        returnValue: _i3.Future<_i6.UserModel?>.value(),
      ) as _i3.Future<_i6.UserModel?>);

  @override
  _i3.Future<List<_i6.UserModel>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i3.Future<List<_i6.UserModel>>.value(<_i6.UserModel>[]),
      ) as _i3.Future<List<_i6.UserModel>>);

  @override
  _i3.Future<List<_i6.UserModel>> getUsersByIds(Iterable<String>? userIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersByIds,
          [userIds],
        ),
        returnValue: _i3.Future<List<_i6.UserModel>>.value(<_i6.UserModel>[]),
      ) as _i3.Future<List<_i6.UserModel>>);

  @override
  _i3.Stream<_i6.UserModel?> watchProfile(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #watchProfile,
          [uid],
        ),
        returnValue: _i3.Stream<_i6.UserModel?>.empty(),
      ) as _i3.Stream<_i6.UserModel?>);

  @override
  _i3.Future<void> updateProfile(
    String? uid,
    Map<String, dynamic>? fields,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [
            uid,
            fields,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addSkill(
    String? uid,
    String? skill,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSkill,
          [
            uid,
            skill,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeSkill(
    String? uid,
    String? skill,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSkill,
          [
            uid,
            skill,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProfile(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [uid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FirestoreReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreReviewRepository extends _i1.Mock
    implements _i7.FirestoreReviewRepository {
  MockFirestoreReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> create(_i8.Review? review) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [review],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i8.Review>> watchForUser(String? targetUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchForUser,
          [targetUserId],
        ),
        returnValue: _i3.Stream<List<_i8.Review>>.empty(),
      ) as _i3.Stream<List<_i8.Review>>);

  @override
  _i3.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
