// Mocks generated by Mockito from annotations
// in taf_match/test/views/js_job_details_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:taf_match/models/notification_model.dart' as _i4;
import 'package:taf_match/repositories/firestore_notification_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreNotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreNotificationRepository extends _i1.Mock
    implements _i2.FirestoreNotificationRepository {
  MockFirestoreNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.AppNotification>> watchForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchForUser,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.AppNotification>>.empty(),
      ) as _i3.Stream<List<_i4.AppNotification>>);

  @override
  _i3.Future<void> create({
    required String? userId,
    required String? title,
    required String? message,
    required String? type,
    String? jobId,
    String? applicationId,
    String? conversationId,
    int? unreadCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #userId: userId,
            #title: title,
            #message: message,
            #type: type,
            #jobId: jobId,
            #applicationId: applicationId,
            #conversationId: conversationId,
            #unreadCount: unreadCount,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertMessageNotification({
    required String? userId,
    required String? conversationId,
    required String? jobId,
    required String? jobTitle,
    required int? unreadCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMessageNotification,
          [],
          {
            #userId: userId,
            #conversationId: conversationId,
            #jobId: jobId,
            #jobTitle: jobTitle,
            #unreadCount: unreadCount,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markAsRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notificationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markAllAsRead(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
